# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sonia Anna Puton
title: Senior Security Engineer
email: sonia.anna@protonmail.com
website: www.github.com/soniaanna

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  soniaanna
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: soniaanna
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi, my name is Sonia, and I am a seasoned Cybersecurity Specialist. Over the years, I've held multiple key roles in the field of cybersecurity, where my primary focus has been the safety and protection of digital assets and infrastructures. My journey began at Akamai, where I started as an SOC Specialist, and I quickly climbed the ranks due to my dedication and expertise. I am knowledgeable in both networking concepts and current security landscape. I have worked in fast-paced environment, while pursuing my own development goals. I am interested in cloud computing, AI and software engineering.

  I am most skilled in: <mark>Network Security</mark> and <mark>Eating Pizza</mark>

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Netguru
        link: netguru.com
        # link_text: boringcompany.com
        sub_title: Senior Security Engineer
        caption: march 2022 - present
        quote: >
          Taking cybersecurity for our clients to next level
        description: | # this will include new lines to allow paragraphs
            At Netguru, I've been leading security projects for clients, analyzing and fine-tuning security requirements of various tools. My tasks include conducting comprehensive security audits, designing robust security policies, and performing penetration tests for clients in healthcare, fintech, and retail sectors. Additionally, I often advise developer teams on security best practices.

      - layout: left
        title: Akamai Technologies
        link: akamai.com
        # link_text: boringcompany.com
        sub_title: Security Architect II
        caption: november 2020 - march 2022 · 1 yr 5 mos
        quote: >
          Making Internet fast, reliable and secure
        description: | # this will include new lines to allow paragraphs
            I was one of the security architect in the Product Development Aligned Services team. My tasks included:
            · Develop best practices for the operations to ensure quality
            · Coordinate with relevant teams to speed go to product delivery
            · Own the technical components of a customer integration project

      - layout: left
        title: Akamai Technologies
        link: akamai.com
        # link_text: boringcompany.com
        sub_title: Security Operations Specialist II
        caption: september 2017 - november 2020 · 3 yrs and 4 mos
        quote: >
          Security management, monitoring, and mitigation. One fully managed service.
        description: | # this will include new lines to allow paragraphs
            My job in Akamai SOC was consisting of:
            · Configuring and troubleshooting WAF and customer integration issues while under attack
            · Development, testing and implementation of security products - including BGP routing tests
            · DDoS attack mitigation on Prolexic platform
            · Customer communications relating to advanced security events
            · Advanced packet analysis to identify complex attack vectors - tcpdump, wireshark
            · Security alerts response calls, providing recommendations
            · Security alerts analysis and investigation - Splunk
            · Subject Matter Expert in bot management, botnet attacks.
            · Automating daily workflows using Python, Docker, Git, Bash.

      - layout: left
        title: Akamai Technologies
        link: akamai.com
        # link_text: boringcompany.com
        sub_title: Academic Intern
        caption: april 2017 - september 2017 · 5 mos
        quote: >
          Security management, monitoring, and mitigation. One fully managed service.
        description: | # this will include new lines to allow paragraphs
            Completed 5 month intensive technical training with weekly assessments in the following topics: 
            Linux | Bash | Databases | SQL | ITIL | Security | Python | Django


  - title: Certifications
    layout: list
    content:
      - layout: top
        title: AWS Certified Security – Specialty
        sub_title: Amazon Web Services Training and Certification
          
      - layout: top
        title: 'Microsoft Certified: Azure Security Engineer Associate'
        sub_title: Microsoft

      - layout: top
        title: AWS Certified Developer – Associate
        sub_title: Amazon Web Services Training and Certification
      
      - layout: top
        title: 'Microsoft Certified: Azure Fundamentals'
        sub_title: Microsoft
      
      - layout: top
        title: CompTIA Cloud+ ce Certification
        sub_title: CompTIA
      
      - layout: top
        title: CompTIA Linux+ ce Certification
        sub_title: CompTIA
      
      - layout: top
        title: Understanding of Cisco Network Devices
        sub_title: Cisco
      
      - layout: top
        title: Cisco Certified Network Associate Routing and Switching (CCNA Routing and Switching)
        sub_title: Cisco


  - title: Professional Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - title: Switching and Routing
        caption: Cisco IOS, BGP
      - title: Security Alerts
        caption: Analysis and Evaluation
      - title: OWASP Expertise
        caption: Understanding of vulnerabilities and mitigation techniques
      - title: Firewall and Security
        caption: ACLs, Snort configuration
      - title: Deep Packet Inspection
        caption: tcpdump, wireshark, Berkeley Packet Filtering, Netflow
      - title: Programming
        caption: Python
      - title: Scripting
        caption: Bash scripting
      - title: Systems Administration
        caption: Linux administration

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AGH, Kraków
        caption: 2018 - 2019
        sub_title: Computer Science - Postgraduate
        description: | # You can fill in additional details or leave blank
          (details about the postgraduate course or experiences)

      - layout: left
        title: AGH, Kraków
        caption: 2013 - 2017
        sub_title: Bachelor of Petroleum Engineering
        description: | # You can fill in additional details or leave blank
          (details about the bachelor's course or experiences)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in cybersecurity, I also enjoy:
      - Sports (gymnastics, calisthenics)
      - Crochet, arts and crafts, painting landscapes
      - Yoga, meditation and all wellness things


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
