theme: jekyll-theme-cayman
title: Sonia Puton - Cybersecurity Specialist
description: Welcome to my personal space! Dive in to explore my projects and insights in the world of cybersecurity.
favicon: /favicon.ico
plugins:
  - jekyll-seo-tag
